/**
 * LogoPreview.jsx — Logo Display & Export Component
 * 
 * Renders the generated SVG logo inline and provides export buttons
 * for both SVG (vector) and PNG (raster) formats.
 * 
 * Uses dangerouslySetInnerHTML to inject the generated SVG string.
 * This is safe here because the SVG is generated by our own code,
 * not from user input.
 */

import { useRef, useCallback } from 'react';
import { downloadSvg, downloadPng } from '../lib/exportUtils';
import { renderSvgToCanvas } from '../lib/canvasUtils';

/**
 * LogoPreview Component
 * 
 * @param {Object} props
 * @param {string} props.svgString - Generated SVG markup string
 * @param {Object} props.logoMeta - Metadata about the logo (initials, icon, style)
 */
export default function LogoPreview({ svgString, logoMeta }) {
  const svgContainerRef = useRef(null);

  /**
   * Export logo as SVG file.
   * Retrieves the SVG element from the DOM and triggers download.
   */
  const handleDownloadSvg = useCallback(() => {
    const svgEl = svgContainerRef.current?.querySelector('svg');
    if (svgEl) downloadSvg(svgEl, 'logo.svg');
  }, []);

  /**
   * Export logo as PNG file.
   * Converts the SVG to a canvas at 4x resolution (800×800)
   * for high-quality output, then downloads as PNG.
   */
  const handleDownloadPng = useCallback(async () => {
    const svgEl = svgContainerRef.current?.querySelector('svg');
    if (!svgEl) return;
    const canvas = await renderSvgToCanvas(svgEl, 800, 800);
    downloadPng(canvas, 'logo.png');
  }, []);

  if (!svgString) return null;

  return (
    <div className="space-y-4 animate-on-mount stagger-1">
      {/* Section Header */}
      <div className="flex items-center gap-3 px-2">
        <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-blue-500/20 to-purple-500/20 border border-blue-500/30 flex items-center justify-center text-blue-400 text-sm shadow-[0_0_10px_rgba(59,130,246,0.1)]">
          🎨
        </div>
        <h2 className="text-xl font-bold text-slate-100 tracking-tight">Logo Design</h2>
      </div>

      {/* Logo Display */}
      <div className="glass-card rounded-3xl p-8 flex flex-col items-center relative overflow-hidden group">
        
        {/* Subtle background glow */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-48 h-48 bg-blue-500/10 blur-3xl rounded-full pointer-events-none transition-opacity opacity-0 group-hover:opacity-100 duration-500"></div>

        {/* SVG Container — white background for logo visibility */}
        <div 
          ref={svgContainerRef}
          className="bg-white rounded-2xl p-8 shadow-[0_8px_30px_rgb(0,0,0,0.12)] border border-slate-200 mb-6 w-64 h-64 flex items-center justify-center relative z-10 transition-transform duration-500 hover:scale-[1.02]"
          dangerouslySetInnerHTML={{ __html: svgString }}
        />

        {/* Logo Metadata */}
        {logoMeta && (
          <div className="text-center mb-6 space-y-1 relative z-10">
            <p className="text-[11px] font-semibold text-slate-500 uppercase tracking-widest">
              Icon: <span className="text-slate-300">{logoMeta.iconName}</span> <span className="mx-1 text-slate-600">•</span> 
              Style: <span className="text-slate-300">{logoMeta.styleTreatment}</span>
            </p>
          </div>
        )}

        {/* Export Buttons */}
        <div className="flex gap-3 relative z-10 w-full sm:w-auto">
          <button
            onClick={handleDownloadSvg}
            className="flex-1 sm:flex-none px-6 py-3 bg-slate-800/80 hover:bg-slate-700 border border-slate-700/50 rounded-xl 
              text-[13px] font-semibold text-white transition-all duration-200 cursor-pointer hover:shadow-lg flex items-center justify-center gap-2"
          >
            <svg className="w-4 h-4 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Vector (SVG)
          </button>
          <button
            onClick={handleDownloadPng}
            className="flex-1 sm:flex-none px-6 py-3 bg-slate-800/80 hover:bg-slate-700 border border-slate-700/50 rounded-xl 
              text-[13px] font-semibold text-white transition-all duration-200 cursor-pointer hover:shadow-lg flex items-center justify-center gap-2"
          >
            <svg className="w-4 h-4 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Image (PNG)
          </button>
        </div>
      </div>
    </div>
  );
}
