/**
 * LogoPreview.jsx — Logo Display & Export Component
 * 
 * Renders the generated SVG logo inline and provides export buttons
 * for both SVG (vector) and PNG (raster) formats.
 * 
 * Uses dangerouslySetInnerHTML to inject the generated SVG string.
 * This is safe here because the SVG is generated by our own code,
 * not from user input.
 */

import { useRef, useCallback } from 'react';
import { downloadSvg, downloadPng } from '../lib/exportUtils';
import { renderSvgToCanvas } from '../lib/canvasUtils';

/**
 * LogoPreview Component
 * 
 * @param {Object} props
 * @param {string} props.svgString - Generated SVG markup string
 * @param {Object} props.logoMeta - Metadata about the logo (initials, icon, style)
 */
export default function LogoPreview({ svgString, logoMeta }) {
  const svgContainerRef = useRef(null);

  /**
   * Export logo as SVG file.
   * Retrieves the SVG element from the DOM and triggers download.
   */
  const handleDownloadSvg = useCallback(() => {
    const svgEl = svgContainerRef.current?.querySelector('svg');
    if (svgEl) downloadSvg(svgEl, 'logo.svg');
  }, []);

  /**
   * Export logo as PNG file.
   * Converts the SVG to a canvas at 4x resolution (800×800)
   * for high-quality output, then downloads as PNG.
   */
  const handleDownloadPng = useCallback(async () => {
    const svgEl = svgContainerRef.current?.querySelector('svg');
    if (!svgEl) return;
    const canvas = await renderSvgToCanvas(svgEl, 800, 800);
    downloadPng(canvas, 'logo.png');
  }, []);

  if (!svgString) return null;

  return (
    <div className="space-y-6">
      {/* Section Header */}
      <div className="flex items-center gap-3">
        <div className="w-8 h-8 rounded-lg bg-blue-500/20 flex items-center justify-center text-blue-400 text-sm">
          🎨
        </div>
        <h2 className="text-xl font-bold text-white">Logo</h2>
      </div>

      {/* Logo Display */}
      <div className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8 flex flex-col items-center">
        {/* SVG Container — white background for logo visibility */}
        <div 
          ref={svgContainerRef}
          className="bg-white rounded-xl p-8 shadow-lg mb-6 w-64 h-64 flex items-center justify-center"
          dangerouslySetInnerHTML={{ __html: svgString }}
        />

        {/* Logo Metadata */}
        {logoMeta && (
          <div className="text-center mb-4 space-y-1">
            <p className="text-xs text-gray-500 uppercase tracking-wider">
              Icon: <span className="text-gray-300">{logoMeta.iconName}</span> • 
              Style: <span className="text-gray-300">{logoMeta.styleTreatment}</span>
            </p>
          </div>
        )}

        {/* Export Buttons */}
        <div className="flex gap-3">
          <button
            onClick={handleDownloadSvg}
            className="px-5 py-2.5 bg-white/10 hover:bg-white/15 border border-white/10 rounded-lg 
              text-sm font-medium text-white transition-all duration-200 cursor-pointer
              hover:border-white/20"
          >
            ⬇ SVG
          </button>
          <button
            onClick={handleDownloadPng}
            className="px-5 py-2.5 bg-white/10 hover:bg-white/15 border border-white/10 rounded-lg 
              text-sm font-medium text-white transition-all duration-200 cursor-pointer
              hover:border-white/20"
          >
            ⬇ PNG
          </button>
        </div>
      </div>
    </div>
  );
}
